sudo: required
dist: focal
language: go
go:
  - 1.19.1
before_install:
  - sudo wget -O opm https://github.com/operator-framework/operator-registry/releases/latest/download/linux-amd64-opm
  - sudo chmod +x opm
  - sudo mv opm /usr/local/bin/opm
script:
  - |
    echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin
    if [ "${TRAVIS_BRANCH}" == "px-rel-1.10.4" ]; then
      export DOCKER_HUB_OPERATOR_TAG=1.10.4-dev
      export DOCKER_HUB_OPERATOR_TEST_TAG=1.10.4-dev
    else
      export DOCKER_HUB_OPERATOR_TAG=`git rev-parse --short HEAD`
      export DOCKER_HUB_OPERATOR_TEST_TAG=`git rev-parse --short HEAD`
    fi
    make vendor-update all test verify-bundle-dir container integration-test integration-test-container &&
    if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      make deploy;
      make integration-test-deploy;
      if [ "${TRAVIS_BRANCH}" == "px-rel-1.10.4" ]; then
        make bundle catalog
      fi
    fi
notifications:
  email:
    on_success: always
    on_failure: always
after_success:
  - bash <(curl -s https://codecov.io/bash)
