sudo: required
dist: trusty
language: go
go:
  - 1.15.x
script:
  - |
    if [ "${TRAVIS_BRANCH}" == "px-rel-1.5.2" ]; then
      export DOCKER_HUB_STORAGE_OPERATOR_TAG=1.5.2-dev
      export DOCKER_HUB_STORAGE_OPERATOR_TEST_TAG=latest
      export BUILD_VER="${TRAVIS_BUILD_NUMBER}"
    else
      export DOCKER_HUB_STORAGE_OPERATOR_TAG=`git rev-parse --short HEAD`
      export DOCKER_HUB_STORAGE_OPERATOR_TEST_TAG=`git rev-parse --short HEAD`
    fi
    make vendor-update && make && make downloads && make test && make verify-catalog && make container && make integration-test && make integration-test-container &&
    if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}";
      make deploy;
      make integration-test-deploy;
      if [ "${TRAVIS_BRANCH}" == "px-rel-1.5.2" ]; then
        make deploy-catalog
      fi
    fi
notifications:
  email:
    on_success: always
    on_failure: always
after_success:
  - bash <(curl -s https://codecov.io/bash)
